analytics: {}
color:
  brandColors:
    - '#FEFEFE'
    - '#FFCE00'
    - '#FEE77F'
    - '#FEDA3C'
    - '#432300'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0
  saturation: 0.512336
cta: {}
layout_spectrum: 0.994243
name: kimmade
opengraph: {}
purpose: []
typography_spectrum: 0.060033
